# Generated by Django 5.2.5 on 2025-09-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_bank', '0003_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
