# Generated by Django 5.2.5 on 2025-09-08 14:45

import client_bank.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_bank', '0004_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=client_bank.models.generate_account_number, max_length=10, unique=True),
        ),
    ]
