# Generated by Django 5.2.5 on 2025-09-12 11:29

import client_bank.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_bank', '0005_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ref',
            field=models.CharField(default=client_bank.models.generateTranscationRef, max_length=64, unique=True),
        ),
    ]
